successful_deliveries = []
version='V3.0'
ResultUrl = 'http://www.pushplus.plus/send'
shixiseng_SearchUrl = "https://apigateway-h3.shixiseng.com/api/interns/v3.0/interns/wxz/search/v4"
shixiseng_GroupUrl = "https://apigateway-h3.shixiseng.com/api/deliver/v3.0/deliver/options"
shixiseng_PostUrl = "https://apigateway-h3.shixiseng.com/api/deliver/v3.0/deliver"
yizhanchi_SearchUrl = "https://api.izhanchi.com/position/recommend/index"
yizhanchi_PostUrl = "https://api.izhanchi.com/user/send/"
yizhanchi_CitylistUrl = "https://api.izhanchi.com/index/citylist"
Bosszhipin_CitylistUrl = "https://www.zhipin.com/wapi/zpCommon/data/cityGroup.json"
Bosszhipin_SearchUrl = "https://www.zhipin.com/wapi/zpgeek/search/joblist.json"
Bosszhipin_PostUrl = "https://www.zhipin.com/wapi/zpgeek/friend/add.json"
zhilianzhaopin_SearchUrl = "https://cgate.zhaopin.com/positionbusiness/searchrecommend/searchPositions"
zhilianzhaopin_PostUrl = "https://cgate.zhaopin.com/positionbusiness/delivery/positionApply"
maimai_SearchUrl = "https://h3.open.taou.com/maimai/search_front/app/job_search"
maimai_PostUrl = "https://maimai.cn/sdk/jobs/job/send_resume"
wubatongcheng_SearchUrl = "https://app.58.com/api/list/quanzhizhaopin"
wubatongcheng_PostUrl = "https://jlwebapp.58.com//resumedelivery/process"